global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'harbe-auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8181' ]
        labels:
          application: 'Auth Service Application'

  - job_name: 'gateway-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Gateway Service Application'

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'Order Service Application'

  - job_name: 'product-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Product Service Application'

  - job_name: 'cart-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'Cart Service Application'
